# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/QQ/soc_lite_top_on_Nexys4.xdc

# IP: ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet
